name: Security Scanning
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip3 install bandit
      - name: Run security scan
        run: |
          bandit -r .
